import { useQuery } from '@powersync/react-native';
import { useRouter } from 'expo-router';
import { ClipboardCheck, ChevronRight, Plus } from 'lucide-react-native';
import { SafeAreaView, ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { AppHeader } from '../../../../components/AppHeader';
import { Button, EmptyState, ListSurface, OperationalRow } from '../../../../components/ui';
import { Breakpoints, Colors, FontFamily, FontSizes, Radius, Spacing, Typography } from '../../../../lib/constants';

type Row={id:string;obra_id:string;equipe_id:string;medicao_id:string|null;data_avaliacao:string;status:string;percentual:string;obra_nome:string;equipe_nome:string;referencia:string|null};
const QUERY=`SELECT a.id,a.obra_id,a.equipe_id,a.medicao_id,a.data_avaliacao,a.status,a.percentual,o.nome obra_nome,e.nome equipe_nome,m.referencia FROM avaliacoes_empreiteiro a JOIN obras o ON o.id=a.obra_id JOIN equipes e ON e.id=a.equipe_id LEFT JOIN medicoes_servico m ON m.id=a.medicao_id ORDER BY a.created_at DESC`;
const PENDING=`SELECT m.id,m.referencia,o.nome obra_nome,e.nome equipe_nome FROM medicoes_servico m JOIN obras o ON o.id=m.obra_id JOIN equipes e ON e.id=m.equipe_id LEFT JOIN avaliacoes_empreiteiro a ON a.medicao_id=m.id AND a.status='concluida' WHERE m.status='rascunho' AND e.tipo='terceirizado' AND a.id IS NULL ORDER BY m.data_medicao DESC`;
export default function EvaluationsScreen(){const router=useRouter();const {data:items,isLoading}=useQuery<Row>(QUERY,[]);const {data:pending}=useQuery<{id:string;referencia:string;obra_nome:string;equipe_nome:string}>(PENDING,[]);return <SafeAreaView style={styles.safe}><AppHeader title="Avaliações" subtitle="Fornecedores de serviço"/><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><View><Text style={styles.heroTitle}>Avaliações em campo</Text><Text style={styles.heroCopy}>{pending.length} {pending.length===1?'medição aguardando avaliação':'medições aguardando avaliação'}</Text></View><View style={styles.heroBadge}><ClipboardCheck size={22} color={Colors.brand}/></View></View>{pending.length?<View style={styles.section}><Text style={styles.title}>Aguardando avaliação</Text><ListSurface>{pending.map((item,index)=><OperationalRow key={item.id} last={index===pending.length-1} onPress={()=>router.push(`/avaliacoes/nova?medicaoId=${item.id}` as never)} accessibilityLabel={`Avaliar medição ${item.referencia}`} trailing={<ChevronRight size={19} color={Colors.textTertiary}/>}><Text style={styles.rowTitle}>{item.referencia}</Text><Text style={styles.rowMeta}>{item.equipe_nome} · {item.obra_nome}</Text></OperationalRow>)}</ListSurface></View>:null}<View style={styles.section}><View style={styles.heading}><Text style={styles.title}>Histórico</Text><Button label="Avulsa" Icon={Plus} variant="secondary" onPress={()=>router.push('/avaliacoes/nova' as never)}/></View>{isLoading?<Text style={styles.muted}>Carregando avaliações...</Text>:items.length?<ListSurface>{items.map((item,index)=><OperationalRow key={item.id} last={index===items.length-1} onPress={()=>{}} accessibilityLabel={`Avaliação de ${item.equipe_nome}`} trailing={<Text style={[styles.score,item.status==='concluida'?styles.ok:styles.muted]}>{item.status==='concluida'?`${Number(item.percentual).toFixed(0)}%`:item.status}</Text>}><Text style={styles.rowTitle}>{item.equipe_nome}</Text><Text style={styles.rowMeta}>{item.obra_nome} · {item.referencia??'Avulsa'} · {item.data_avaliacao}</Text></OperationalRow>)}</ListSurface>:<EmptyState Icon={ClipboardCheck} title="Nenhuma avaliação registrada" description="As avaliações concluídas no campo aparecerão aqui."/>}</View></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.bg},content:{width:'100%',maxWidth:Breakpoints.maxContent,alignSelf:'center',padding:Spacing.lg,paddingBottom:110,gap:Spacing.xl},hero:{backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,padding:Spacing.lg,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},heroTitle:{...Typography.heading,color:Colors.text},heroCopy:{...Typography.caption,color:Colors.textSecondary,marginTop:4},heroBadge:{width:46,height:46,borderRadius:Radius.md,backgroundColor:Colors.brandLight,alignItems:'center',justifyContent:'center'},section:{gap:Spacing.sm},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{...Typography.heading,color:Colors.text},rowTitle:{fontFamily:FontFamily.semibold,fontSize:FontSizes.base,color:Colors.text},rowMeta:{...Typography.caption,color:Colors.textSecondary,marginTop:3},score:{fontFamily:FontFamily.monoSemibold,fontSize:FontSizes.base},ok:{color:Colors.ok},muted:{color:Colors.textTertiary}});
