"use strict";(()=>{var e={};e.id=10,e.ids=[10],e.modules={2934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},4580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},5869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},4624:(e,o,r)=>{r.r(o),r.d(o,{originalPathname:()=>f,patchFetch:()=>x,requestAsyncStorage:()=>m,routeModule:()=>u,serverHooks:()=>h,staticGenerationAsyncStorage:()=>d});var t={};r.r(t),r.d(t,{GET:()=>c,dynamic:()=>p});var s=r(3036),a=r(5736),n=r(5262),l=r(3244),i=r(2798);let p="force-dynamic";async function c(e){let o=new URL(e.url).searchParams.get("obraId"),r=await (0,l.e)(),{data:t,error:s}=await r.rpc("get_obras_com_fvs");if(s)return console.error("Erro ao exportar progresso:",s),Response.json({error:"N\xe3o foi poss\xedvel exportar o progresso das obras."},{status:500});let a=(t??[]).filter(e=>!o||e.id===o);return(0,i.m)("progresso-obras.xls","Progresso de obras",[{header:"Obra",value:e=>e.nome},{header:"Empresa",value:e=>e.empresa_nome},{header:"Munic\xedpio",value:e=>e.municipio},{header:"UF",value:e=>e.uf},{header:"Status",value:e=>e.status},{header:"Ambientes",value:e=>e.total_ambientes},{header:"FVS totais",value:e=>e.total_fvs},{header:"FVS conclu\xeddas",value:e=>e.fvs_concluidas},{header:"Progresso (%)",value:e=>Math.round((e.progresso_percentual??0)*100)/100},{header:"NCs abertas",value:e=>e.ncs_abertas}],a)}let u=new s.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/(admin)/relatorios/export/progresso/route",pathname:"/relatorios/export/progresso",filename:"route",bundlePath:"app/(admin)/relatorios/export/progresso/route"},resolvedPagePath:"C:\\Code\\prumoq\\apps\\web\\app\\(admin)\\relatorios\\export\\progresso\\route.ts",nextConfigOutput:"standalone",userland:t}),{requestAsyncStorage:m,staticGenerationAsyncStorage:d,serverHooks:h}=u,f="/(admin)/relatorios/export/progresso/route";function x(){return(0,n.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:d})}},2798:(e,o,r)=>{function t(e){return String(e??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;")}function s(e,o,r,s){let a=r.map(e=>`<Cell ss:StyleID="Header"><Data ss:Type="String">${t(e.header)}</Data></Cell>`).join(""),n=s.map(e=>`<Row>${r.map(o=>{let r=o.value(e),s="number"==typeof r?"Number":"String";return`<Cell><Data ss:Type="${s}">${t(r)}</Data></Cell>`}).join("")}</Row>`).join(""),l=`<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Styles>
  <Style ss:ID="Default"><Alignment ss:Vertical="Center"/><Font ss:FontName="Arial" ss:Size="10"/></Style>
  <Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#163B50" ss:Pattern="Solid"/></Style>
 </Styles>
 <Worksheet ss:Name="${t(o.slice(0,31))}">
  <Table>
   <Row ss:Height="22">${a}</Row>
   ${n}
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>1</SplitHorizontal><TopRowBottomPane>1</TopRowBottomPane></WorksheetOptions>
 </Worksheet>
</Workbook>`;return new Response(`\uFEFF${l}`,{headers:{"Content-Type":"application/vnd.ms-excel; charset=utf-8","Content-Disposition":`attachment; filename="${e.replaceAll('"',"")}"`,"Cache-Control":"private, no-store"}})}r.d(o,{m:()=>s})},3244:(e,o,r)=>{r.d(o,{e:()=>a});var t=r(6603),s=r(9362);async function a(){let e=await (0,s.cookies)();return(0,t.createServerClient)("https://xdeyoxdtfbueuymvbsbl.supabase.co","sb_publishable_f2BZJspm9XZyeXjhO_e51Q_iQb3iblG",{cookies:{getAll:()=>e.getAll(),setAll(o){try{o.forEach(({name:o,value:r,options:t})=>e.set(o,r,t))}catch(e){}}}})}},3036:(e,o,r)=>{e.exports=r(517)}};var o=require("../../../../../webpack-runtime.js");o.C(e);var r=e=>o(o.s=e),t=o.X(0,[522,920],()=>r(4624));module.exports=t})();