"use strict";(()=>{var e={};e.id=349,e.ids=[349],e.modules={2934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},4580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},5869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},3778:(e,o,r)=>{r.r(o),r.d(o,{originalPathname:()=>x,patchFetch:()=>h,requestAsyncStorage:()=>u,routeModule:()=>m,serverHooks:()=>f,staticGenerationAsyncStorage:()=>d});var t={};r.r(t),r.d(t,{GET:()=>p,dynamic:()=>c});var a=r(3036),s=r(5736),n=r(5262),l=r(3244),i=r(2798);let c="force-dynamic";async function p(e){let{searchParams:o}=new URL(e.url),r=o.get("obraId"),t=o.get("from"),a=o.get("to"),s=await (0,l.e)(),{data:n,error:c}=await s.rpc("get_ncs_full");if(c)return console.error("Erro ao exportar NCs:",c),Response.json({error:"N\xe3o foi poss\xedvel exportar as n\xe3o conformidades."},{status:500});let p=(n??[]).filter(e=>(!r||e.obra_id===r)&&(!t||!e.prazo_correcao||e.prazo_correcao>=t)&&(!a||!e.prazo_correcao||e.prazo_correcao<=a));return(0,i.m)("nao-conformidades.xls","N\xe3o conformidades",[{header:"Obra",value:e=>e.obra_nome},{header:"Ambiente",value:e=>e.ambiente_nome},{header:"Item",value:e=>e.item_titulo},{header:"Descri\xe7\xe3o",value:e=>e.descricao},{header:"Respons\xe1vel",value:e=>e.responsavel_nome},{header:"Prioridade",value:e=>e.prioridade},{header:"Status",value:e=>e.status},{header:"Prazo de corre\xe7\xe3o",value:e=>{var o;return(o=e.prazo_correcao)?new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo"}).format(new Date(`${o}T12:00:00-03:00`)):""}}],p)}let m=new a.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/(admin)/relatorios/export/ncs/route",pathname:"/relatorios/export/ncs",filename:"route",bundlePath:"app/(admin)/relatorios/export/ncs/route"},resolvedPagePath:"C:\\Code\\prumoq\\apps\\web\\app\\(admin)\\relatorios\\export\\ncs\\route.ts",nextConfigOutput:"standalone",userland:t}),{requestAsyncStorage:u,staticGenerationAsyncStorage:d,serverHooks:f}=m,x="/(admin)/relatorios/export/ncs/route";function h(){return(0,n.patchFetch)({serverHooks:f,staticGenerationAsyncStorage:d})}},2798:(e,o,r)=>{function t(e){return String(e??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;")}function a(e,o,r,a){let s=r.map(e=>`<Cell ss:StyleID="Header"><Data ss:Type="String">${t(e.header)}</Data></Cell>`).join(""),n=a.map(e=>`<Row>${r.map(o=>{let r=o.value(e),a="number"==typeof r?"Number":"String";return`<Cell><Data ss:Type="${a}">${t(r)}</Data></Cell>`}).join("")}</Row>`).join(""),l=`<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Styles>
  <Style ss:ID="Default"><Alignment ss:Vertical="Center"/><Font ss:FontName="Arial" ss:Size="10"/></Style>
  <Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#163B50" ss:Pattern="Solid"/></Style>
 </Styles>
 <Worksheet ss:Name="${t(o.slice(0,31))}">
  <Table>
   <Row ss:Height="22">${s}</Row>
   ${n}
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>1</SplitHorizontal><TopRowBottomPane>1</TopRowBottomPane></WorksheetOptions>
 </Worksheet>
</Workbook>`;return new Response(`\uFEFF${l}`,{headers:{"Content-Type":"application/vnd.ms-excel; charset=utf-8","Content-Disposition":`attachment; filename="${e.replaceAll('"',"")}"`,"Cache-Control":"private, no-store"}})}r.d(o,{m:()=>a})},3244:(e,o,r)=>{r.d(o,{e:()=>s});var t=r(6603),a=r(9362);async function s(){let e=await (0,a.cookies)();return(0,t.createServerClient)("https://xdeyoxdtfbueuymvbsbl.supabase.co","sb_publishable_f2BZJspm9XZyeXjhO_e51Q_iQb3iblG",{cookies:{getAll:()=>e.getAll(),setAll(o){try{o.forEach(({name:o,value:r,options:t})=>e.set(o,r,t))}catch(e){}}}})}},3036:(e,o,r)=>{e.exports=r(517)}};var o=require("../../../../../webpack-runtime.js");o.C(e);var r=e=>o(o.s=e),t=o.X(0,[522,920],()=>r(3778));module.exports=t})();