'use client';

import { useMemo, useState, useTransition } from 'react';
import { AlertTriangle, Ban, CheckCircle2, Plus, Ruler, Trash2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useToast } from '@/components/ui/Toast';
import type { Database } from '@prumoq/shared';
import { approveMeasurement, cancelMeasurement, discardMeasurement, getMeasurementDetail, loadMeasurementOptions, saveMeasurementDraft, type MeasurementDraftInput } from './actions';
import MeasurementDetailModal from './MeasurementDetailModal';

type Work={id:string;nome:string;controle_medicoes_efetivo:boolean};type Team={id:string;nome:string;tipo:string};type WorkTeam={obra_id:string;equipe_id:string};
type Indicator=Database['public']['Views']['vw_indicadores_medicoes']['Row'];type Measurement=Database['public']['Tables']['medicoes_servico']['Row'];
type ItemTotal={medicao_id:string;valor_calculado:number;quantidade_periodo:number;tipo:Database['public']['Enums']['tipo_item_medicao']};
type Balance=Database['public']['Views']['vw_saldos_medicao_servico']['Row'];type PlannedService={id:string;subservico:string|null};type PendingImpact={id:string;descricao:string;prazo_avaliacao:string|null};
type Release={id:string;vinculacaoId:string;verificacaoId:string;fvsId:string;service:string;stage:string|null;previous:number;current:number;quantity:number;unit:string;unitPrice:number|null};
type Rework={ncId:string;vinculacaoId:string;service:string;description:string;value:number;category:string|null};
const today=()=>new Date().toISOString().slice(0,10);const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const num=(n:number|null|undefined)=>Number(n??0).toLocaleString('pt-BR',{maximumFractionDigits:4});

export default function MeasurementsClient({works,indicators,measurements,teams,workTeams,itemTotals,balances,plannedServices,pendingImpacts}:{works:Work[];indicators:Indicator[];measurements:Measurement[];teams:Team[];workTeams:WorkTeam[];itemTotals:ItemTotal[];balances:Balance[];plannedServices:PlannedService[];pendingImpacts:PendingImpact[]}){
 const {toast}=useToast();const router=useRouter();const[pending,startTransition]=useTransition();const[open,setOpen]=useState(false);const[obraId,setObraId]=useState(works[0]?.id??'');const[equipeId,setEquipeId]=useState('');const[reference,setReference]=useState('');const[start,setStart]=useState(today());const[end,setEnd]=useState(today());const[date,setDate]=useState(today());const[notes,setNotes]=useState('');const[releases,setReleases]=useState<Release[]>([]);const[rework,setRework]=useState<Rework[]>([]);const[selected,setSelected]=useState<Set<string>>(new Set());const[allocations,setAllocations]=useState<Record<string,string>>({});const[selectedRework,setSelectedRework]=useState<Set<string>>(new Set());const[loading,setLoading]=useState(false);const[cancel,setCancel]=useState<Measurement|null>(null);const[reason,setReason]=useState('');const[detailMeasurement,setDetailMeasurement]=useState<Measurement|null>(null);const[detail,setDetail]=useState<Awaited<ReturnType<typeof getMeasurementDetail>>|null>(null);const[detailLoading,setDetailLoading]=useState(false);
 function openDetail(m:Measurement){setDetailMeasurement(m);setDetail(null);setDetailLoading(true);startTransition(async()=>{const result=await getMeasurementDetail(m.id);setDetailLoading(false);if(result.success)setDetail(result);else toast(result.error??'Falha ao carregar detalhe.','error');});}
 const availableTeams=teams.filter(team=>workTeams.some(row=>row.obra_id===obraId&&row.equipe_id===team.id)); const indicator=indicators.reduce((a,i)=>({value:a.value+Number(i.valor_disponivel??0),measuredValue:a.measuredValue+Number(i.valor_medido??0),blockedValue:a.blockedValue+Number(i.valor_bloqueado??0),estimated:a.estimated+Number(i.custo_estimado_retrabalho??0),confirmed:a.confirmed+Number(i.custo_confirmado_retrabalho??0)}),{value:0,measuredValue:0,blockedValue:0,estimated:0,confirmed:0});
 const selectedReleases=releases.filter(r=>selected.has(r.id)).map(r=>({...r,quantity:Number((allocations[r.id]??String(r.quantity)).replace(',','.'))}));const allocationsValid=selectedReleases.every(r=>Number.isFinite(r.quantity)&&r.quantity>0&&r.quantity<=(releases.find(source=>source.id===r.id)?.quantity??0));const selectedCosts=rework.filter(r=>selectedRework.has(r.ncId));const totalValue=selectedReleases.reduce((sum,r)=>sum+r.quantity*(r.unitPrice??0),0)+selectedCosts.reduce((sum,r)=>sum+r.value,0);
 async function chooseTeam(id:string){setEquipeId(id);setLoading(true);setSelected(new Set());setAllocations({});setSelectedRework(new Set());const result=await loadMeasurementOptions(obraId,id);setLoading(false);if(!result.success){toast(result.error??'Falha ao carregar saldos.','error');return;}setReleases(result.releases as Release[]);setRework(result.rework as Rework[]);}
 function save(){if(!allocationsValid)return toast('Revise as quantidades selecionadas.','error');if(end<start)return toast('Período final deve ser igual ou posterior ao período inicial.','error');if(date<start||date>end)return toast('Data da medição deve estar dentro do período informado.','error');const groups=new Map<string,Release[]>();selectedReleases.forEach(r=>groups.set(r.vinculacaoId,[...(groups.get(r.vinculacaoId)??[]),r]));const itens:MeasurementDraftInput['itens']=Array.from(groups.entries()).map(([link,list])=>{const quantity=list.reduce((s,r)=>s+r.quantity,0);const last=list.at(-1)!;return{vinculacao_id:link,verificacao_id:last.verificacaoId,nc_id:null,tipo:'avanco',quantidade_anterior:Math.min(...list.map(r=>r.previous)),quantidade_atual:Math.min(...list.map(r=>r.previous))+quantity,quantidade_periodo:quantity,quantidade_bloqueada:0,unidade:last.unit,preco_unitario:last.unitPrice,valor_calculado:quantity*(last.unitPrice??0),liberacoes:list.map(r=>({avanco_id:r.id,quantidade:r.quantity}))}});selectedCosts.forEach(cost=>itens.push({vinculacao_id:cost.vinculacaoId,verificacao_id:null,nc_id:cost.ncId,tipo:'retrabalho',quantidade_anterior:0,quantidade_atual:0,quantidade_periodo:0,quantidade_bloqueada:0,unidade:'serviço',preco_unitario:null,valor_calculado:cost.value,liberacoes:[]}));startTransition(async()=>{const result=await saveMeasurementDraft({medicaoId:null,obraId,equipeId,referencia:reference,periodoInicio:start,periodoFim:end,dataMedicao:date,observacao:notes||null,itens});if(!result.success)return toast(result.error??'Falha ao salvar.','error');toast('Medição salva em rascunho.','success');setOpen(false);router.refresh();});}
 function approve(item:Measurement){startTransition(async()=>{const result=await approveMeasurement(item.id,item.obra_id);if(!result.success)return toast(result.error??'Falha ao aprovar.','error');toast('Medição aprovada.','success');router.refresh();});}
 function discard(item:Measurement){startTransition(async()=>{const result=await discardMeasurement(item.id,item.obra_id);if(!result.success)return toast(result.error??'Falha ao descartar.','error');toast('Rascunho descartado e liberações restauradas.','success');router.refresh();});}
 function confirmCancel(){if(!cancel)return;startTransition(async()=>{const result=await cancelMeasurement(cancel.id,cancel.obra_id,reason);if(!result.success)return toast(result.error??'Falha ao cancelar.','error');toast('Medição cancelada e saldo restaurado.','success');setCancel(null);router.refresh();});}
 const ready=balances.filter(row=>Number(row.disponivel??0)>0);const blocked=balances.filter(row=>Number(row.bloqueado??0)>0);const serviceName=(id:string|null)=>plannedServices.find(service=>service.id===id)?.subservico??'Serviço';
 const measurementSummaries=useMemo(()=>{const summaries=new Map<string,{count:number;value:number;hasRnc:boolean}>();for(const item of itemTotals){const current=summaries.get(item.medicao_id)??{count:0,value:0,hasRnc:false};current.count+=1;current.value+=Number(item.valor_calculado);current.hasRnc=current.hasRnc||item.tipo==='retrabalho';summaries.set(item.medicao_id,current);}return summaries;},[itemTotals]);
 return <div className="space-y-5"><section className="flex flex-col gap-4 rounded-xl border border-brd-0 bg-bg-1 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-txt-3">Controle financeiro de serviços</p><h1 className="mt-1 text-2xl font-semibold text-txt">Medições</h1><p className="mt-1 text-sm text-txt-2">Liberações aprovadas, bloqueios e crédito por empreiteiro.</p></div><button onClick={()=>setOpen(true)} disabled={!works.length} className="inline-flex items-center justify-center gap-2 rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Plus size={16}/>Nova medição</button></section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Valor disponível" value={money(indicator.value)} tone="ok"/><Kpi label="Valor medido" value={money(indicator.measuredValue)}/><Kpi label="Valor bloqueado por RNC" value={money(indicator.blockedValue)} tone="nok"/><Kpi label="Retrabalho estimado" value={money(indicator.estimated)}/><Kpi label="Retrabalho confirmado" value={money(indicator.confirmed)} tone="nok"/></section>
 <section className="grid gap-4 lg:grid-cols-3"><ActionList title="Prontos para medir" empty="Nenhum serviço com saldo liberado." rows={ready.slice(0,8).map(row=>({id:row.vinculacao_id??'',title:serviceName(row.fvs_planejada_id),detail:`${num(row.disponivel)} ${row.unidade??''} · ${money(Number(row.valor_disponivel??0))}`,tone:'ok'}))}/><ActionList title="Bloqueados por NC" empty="Nenhum saldo bloqueado." rows={blocked.slice(0,8).map(row=>({id:row.vinculacao_id??'',title:serviceName(row.fvs_planejada_id),detail:`${num(row.bloqueado)} ${row.unidade??''} bloqueados`,tone:'nok'}))}/><div className="overflow-hidden rounded-xl border border-brd-0 bg-bg-1"><div className="border-b border-brd-0 px-4 py-3 text-sm font-semibold text-txt">Impactos em avaliação</div>{pendingImpacts.length?pendingImpacts.slice(0,8).map(item=><Link key={item.id} href={`/nc/${item.id}`} className="block border-b border-brd-0 px-4 py-3 last:border-0 hover:bg-bg-0"><div className="line-clamp-1 text-xs font-semibold text-txt">{item.descricao}</div><div className="mt-1 text-[11px] text-warn">Prazo: {item.prazo_avaliacao??'não definido'}</div></Link>):<div className="px-4 py-6 text-center text-xs text-txt-3">Nenhum impacto aguardando definição.</div>}</div></section>
 <section className="overflow-hidden rounded-xl border border-brd-0 bg-bg-1"><div className="border-b border-brd-0 px-5 py-3 text-sm font-semibold text-txt">Medições realizadas</div>{measurements.length?measurements.map(m=>{const work=works.find(w=>w.id===m.obra_id);const team=teams.find(t=>t.id===m.equipe_id);const summary=measurementSummaries.get(m.id)??{count:0,value:0,hasRnc:false};return <div key={m.id} className="flex flex-col gap-3 border-b border-brd-0 px-5 py-4 last:border-0 hover:bg-bg-0 md:flex-row md:items-center"><button type="button" onClick={()=>openDetail(m)} className="flex flex-1 flex-col gap-1 text-left min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-txt">{m.referencia} · {work?.nome}</span>{summary.hasRnc?<span className="inline-flex items-center gap-1 rounded-full bg-nok-bg px-2 py-0.5 text-[10px] font-semibold text-nok"><AlertTriangle size={10}/>RNC</span>:null}</div><div className="text-xs text-txt-3">{team?.nome} · {m.periodo_inicio} a {m.periodo_fim} · {m.data_medicao} · {summary.count} {summary.count===1?'item':'itens'} · {money(summary.value)}</div></button><span className={`rounded-full px-2 py-1 text-[11px] font-medium ${m.status==='aprovada'?'bg-ok-bg text-ok':m.status==='cancelada'?'bg-nok-bg text-nok':'bg-warn-bg text-warn'}`}>{m.status}</span>{m.status==='rascunho'?<><button onClick={()=>approve(m)} disabled={pending} className="inline-flex items-center gap-1 text-xs font-semibold text-ok"><CheckCircle2 size={14}/>Aprovar</button><button onClick={()=>discard(m)} disabled={pending} className="inline-flex items-center gap-1 text-xs text-nok"><Trash2 size={14}/>Descartar</button></>:m.status==='aprovada'?<button onClick={()=>{setCancel(m);setReason('')}} className="inline-flex items-center gap-1 text-xs text-nok"><Ban size={14}/>Cancelar</button>:null}</div>}):<div className="p-8 text-center text-sm text-txt-3">Nenhuma medição registrada.</div>}</section>
 {open?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-xl bg-bg-1 p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-txt">Nova medição</h2><button onClick={()=>setOpen(false)} className="text-sm text-txt-3">Fechar</button></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Field label="Obra"><select value={obraId} onChange={e=>{setObraId(e.target.value);setEquipeId('');setReleases([])}}>{works.map(w=><option key={w.id} value={w.id}>{w.nome}</option>)}</select></Field><Field label="Empreiteiro"><select value={equipeId} onChange={e=>void chooseTeam(e.target.value)}><option value="">Selecione</option>{availableTeams.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select></Field><Field label="Referência"><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="BM 08"/></Field><Field label="Período inicial"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Período final"><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="Data da medição"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field></div><Field label="Observação"><textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)}/></Field>
 <div className="mt-5"><h3 className="text-sm font-semibold text-txt">Liberações aprovadas</h3><p className="mt-1 text-xs text-txt-3">Selecione a liberação e informe quanto será medido neste período.</p>{loading?<p className="mt-2 text-xs text-txt-3">Carregando...</p>:releases.length?<div className="mt-2 space-y-2">{releases.map(r=>{const checked=selected.has(r.id);return <div key={r.id} className="flex flex-col gap-3 rounded-lg border border-brd-0 bg-bg-0 p-3 sm:flex-row sm:items-center"><label className="flex min-w-0 flex-1 items-center gap-3"><input type="checkbox" checked={checked} onChange={e=>{setSelected(current=>{const next=new Set(current);e.target.checked?next.add(r.id):next.delete(r.id);return next});if(e.target.checked)setAllocations(current=>({...current,[r.id]:current[r.id]??String(r.quantity)}))}}/><div className="min-w-0 flex-1 text-xs"><b className="text-txt">{r.service}{r.stage?` · ${r.stage}`:''}</b><div className="text-txt-3">{num(r.previous)} → {num(r.current)} {r.unit} · saldo desta liberação {num(r.quantity)} {r.unit}</div></div></label>{checked?<label className="text-xs text-txt-2">Medir agora<input className="ml-2 w-28 rounded-md border border-brd-1 bg-bg-1 px-2 py-1.5 text-right" inputMode="decimal" value={allocations[r.id]??String(r.quantity)} onChange={e=>setAllocations(current=>({...current,[r.id]:e.target.value}))}/><span className="ml-1">{r.unit}</span></label>:<div className="text-xs font-semibold text-txt">{money(r.quantity*(r.unitPrice??0))}</div>}</div>})}</div>:equipeId?<p className="mt-2 rounded-lg bg-bg-0 p-3 text-xs text-txt-3">Nenhuma liberação disponível para este empreiteiro.</p>:null}</div>
 {rework.length?<div className="mt-5"><h3 className="text-sm font-semibold text-txt">Retrabalho confirmado</h3><p className="mt-1 text-xs text-txt-3">Custo separado, sem aumentar o avanço físico.</p><div className="mt-2 space-y-2">{rework.map(r=><label key={r.ncId} className="flex items-center gap-3 rounded-lg border border-warn/20 bg-warn-bg p-3"><input type="checkbox" checked={selectedRework.has(r.ncId)} onChange={e=>setSelectedRework(current=>{const next=new Set(current);e.target.checked?next.add(r.ncId):next.delete(r.ncId);return next})}/><div className="flex-1 text-xs"><b>{r.service}</b><div>{r.description}</div></div><b className="text-xs">{money(r.value)}</b></label>)}</div></div>:null}
 <div className="mt-5 rounded-lg border border-brand/20 bg-brand/5 p-4"><div className="grid gap-2 text-xs sm:grid-cols-3"><span>Saldo aprovado selecionado: <b>{num(releases.filter(r=>selected.has(r.id)).reduce((s,r)=>s+r.quantity,0))}</b></span><span>Nova medição: <b>{num(selectedReleases.reduce((s,r)=>s+r.quantity,0))}</b></span><span>Valor total: <b>{money(totalValue)}</b></span></div><p className="mt-2 text-xs text-txt-2">Crédito para: <b>{teams.find(t=>t.id===equipeId)?.nome??'selecione o empreiteiro'}</b></p>{!allocationsValid?<p className="mt-2 text-xs font-medium text-nok">A quantidade deve ser maior que zero e não pode superar o saldo da liberação.</p>:null}</div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-lg bg-bg-2 px-4 py-2 text-xs">Cancelar</button><button onClick={save} disabled={pending||!allocationsValid||!reference.trim()||!equipeId||(!selected.size&&!selectedRework.size)} className="rounded-lg bg-brand px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{pending?'Salvando...':'Salvar rascunho'}</button></div></div></div>:null}
 {detailMeasurement?detailLoading?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div className="rounded-xl bg-bg-1 p-6 text-sm text-txt-2">Carregando detalhe da medição...</div></div>:detail&&detail.success?<MeasurementDetailModal detail={detail.detail} onClose={()=>{setDetailMeasurement(null);setDetail(null)}}/>:null:null}
 {cancel?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div className="w-full max-w-md rounded-xl bg-bg-1 p-5"><div className="flex items-center gap-2 text-nok"><AlertTriangle size={18}/><h2 className="font-semibold">Cancelar {cancel.referencia}</h2></div><p className="mt-2 text-xs text-txt-2">O saldo das liberações será restaurado. O histórico continuará visível.</p><Field label="Justificativa"><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setCancel(null)} className="rounded-lg bg-bg-2 px-4 py-2 text-xs">Voltar</button><button onClick={confirmCancel} disabled={pending||reason.trim().length<3} className="rounded-lg bg-nok px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">Confirmar cancelamento</button></div></div></div>:null}</div>;
}
function Kpi({label,value,tone}:{label:string;value:string;tone?:'ok'|'nok'}){return <div className="rounded-xl border border-brd-0 bg-bg-1 p-4"><div className="text-[10px] font-semibold uppercase text-txt-3">{label}</div><div className={`mt-1 text-lg font-semibold ${tone==='ok'?'text-ok':tone==='nok'?'text-nok':'text-txt'}`}>{value}</div></div>}
function ActionList({title,empty,rows}:{title:string;empty:string;rows:{id:string;title:string;detail:string;tone:'ok'|'nok'}[]}){return <div className="overflow-hidden rounded-xl border border-brd-0 bg-bg-1"><div className="border-b border-brd-0 px-4 py-3 text-sm font-semibold text-txt">{title}</div>{rows.length?rows.map(row=><div key={row.id} className="border-b border-brd-0 px-4 py-3 last:border-0"><div className="line-clamp-1 text-xs font-semibold text-txt">{row.title}</div><div className={`mt-1 text-[11px] ${row.tone==='ok'?'text-ok':'text-nok'}`}>{row.detail}</div></div>):<div className="px-4 py-6 text-center text-xs text-txt-3">{empty}</div>}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-3 block text-xs font-medium text-txt-2">{label}<span className="mt-1 block [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-brd-1 [&_input]:bg-bg-0 [&_input]:px-2.5 [&_input]:py-2 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-brd-1 [&_select]:bg-bg-0 [&_select]:px-2.5 [&_select]:py-2 [&_textarea]:w-full [&_textarea]:rounded-md [&_textarea]:border [&_textarea]:border-brd-1 [&_textarea]:bg-bg-0 [&_textarea]:px-2.5 [&_textarea]:py-2">{children}</span></label>}
